import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
est = pd.read_csv("bm_data.csv", header=None, names=["theta", "phi"])
true_pos = [1.047197, 0.698132]
R_e = 6.3781e6
plt.figure(0)
plt.scatter(est["theta"], est["phi"], alpha=0.5)
plt.scatter(true_pos[0], true_pos[1], alpha=1, c='red', label="True location")
plt.scatter(np.mean(est["theta"]), np.mean(est["phi"]), c='green', marker='x', label="Mean estimate")
plt.grid()
stddev = np.std(est)
plt.xlim(true_pos[0]-0.005, true_pos[0]+0.005)
plt.ylim(true_pos[1]-0.005, true_pos[1]+0.005)
# plt.xticks(np.linspace(true_pos[0]-0.005, true_pos[0]+0.005, 5))
plt.xlabel("Theta (rad)")
plt.ylabel("Phi (rad)")
plt.title(f"Estimates of location using BM method\n95% confidence intervals : X = {R_e*np.sin(true_pos[0])*2*stddev['phi']/1e3:.2f} km, Y = {R_e*2*stddev['theta']/1e3:.2f} km")
plt.legend()
plt.savefig("plot_cluster_bm.png")
plt.show()
print(f"Stddev for theta = {stddev['theta']}, Stddev for phi = {stddev['phi']}")
print(f"95% confidence intervals : X = {R_e*np.sin(true_pos[0])*2*stddev['phi']/1e3:.6f} km, Y = {R_e*2*stddev['theta']/1e3:.6f} km")
# plt.figure(1)
# bm_est = pd.read_csv("bm_data.csv", header=None, names=["theta", "phi"])
# fm_est = pd.read_csv("fm_data_nm.csv" , header=None, names=["theta", "phi"])
# combined_est = pd.read_csv("combined_data.csv", header=None, names=["theta", "phi"])
# plt.scatter(bm_est["theta"], bm_est["phi"], alpha=0.3, c='blue')
# plt.scatter(fm_est["theta"], fm_est["phi"], alpha=0.3, c='orange')
# plt.scatter(true_pos[0], true_pos[1], alpha=1, c='red',marker='x', label="True location")
# plt.scatter(combined_est["theta"], combined_est["phi"], alpha=0.5, c='green')
# plt.xlabel("Theta (rad)")
# plt.ylabel("Phi (rad)")
# plt.xlim(true_pos[0]-0.005, true_pos[0]+0.005)
# plt.ylim(true_pos[1]-0.005, true_pos[1]+0.005)
# plt.grid()
# plt.show()